name = "my-dictionary-pages"
main = "index.ts"  # 上記で作成したファイルのパス（srcの中なら src/index.ts）
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "wrangler"
database_id = "29810d15-4f98-4b82-bebe-dcc7ea16820a"
