# 1. 一番上に以下の3行を新しく追加します
[assets]
directory = "./dist"

# 2. 元々あった設定をそのまま続けます（プロジェクト名は元のまま）
name = "my-dictionary-pages"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[vars]
# VITE_MSAL_CLIENT_ID = "your-client-id"

[[d1_databases]]
binding = "DB"
database_name = "wrangler"
database_id = "29810d15-4f98-4b82-bebe-dcc7ea16820a"
